### ISSUE TITLE
Case sensitive fork creation

### ISSUE THREAD

**Issue by alextrical** [ublue-os/images-website#12]
I have just tried the web interface for creating a new forked OS, and it was a very pleasant process.
The only issue I came across was the request to name the repository, let me enter upper case characters, however it seems that once the find and replace operation is completed, it results in commands similar to
`sudo rpm-ostree rebase ostree-unverified-registry:ghcr.io/alextrical/Kinonite-Makerspace:latest`

However running this command results in the following error
```
Pulling manifest: ostree-image-signed:docker://ghcr.io/alextrical/Kinonite-Makerspace:latest
error: Creating importer: Failed to invoke skopeo proxy method OpenImage: remote error: invalid reference format: repository name must be lowercase
```

If a note could be placed on the website to use lowercase, or apply some form of case lock or replacement in the WebUI or the search and replace process, that could fix this minor issue for future users

**Comment by xynydev** [comment]
I think just lowercasing the search and replace would be fine, I'll look into that when I get to it.
