### ISSUE TITLE
Cosign Key step for Automatic Setups

### ISSUE THREAD

**Issue by 13zebras** [ublue-os/images-website#13]
Under both the Automatic setup (web) and Automatic setup (cli), no mention is made of the need to go through the process of installing the cosign key app and creating a cosign key.

The only place this is mentioned is under the Manual setup page.

Separating out the cosign key section of the Manual setup into a separate page, and pointing it out on all the setup pages would be helpful to everyone, even someone experienced who might still opt for the automatic setup options.

**Comment by xynydev** [comment]
AFAIK both of the automatic options prompt to generate a cosign key during the wizard, actually the main point of them is the mostly automatic generation of keys.

So I'm not following; why should manual instructions be supplied with the automatic options, when the point of the automatic options is not needing manual instruction?
