### ISSUE TITLE
Edit boot_menu.yaml to point at new fork

### ISSUE THREAD

**Issue by alextrical** [ublue-os/images-website#14]
It seems that the boot_menu.yaml  still points at the original repo and as a result doesn't download the intended OS. I believe this is something that could be added to the automation.

**Comment by xynydev** [comment]
Sure! This shouldn't be hard.

**Comment by xynydev** [comment]
[6899b96](https://github.com/ublue-os/images-website/commit/6899b96ff6b1c3a168814fd6f4e6bce0d1342386)
