### ISSUE TITLE
Error: process completed with exit code 127

### ISSUE THREAD

**Issue by gluckgluckwasserbauch** [ublue-os/images-website#20]
No matter what image I want to fork with the web tool, I always get the same error message for hours now.
I was able to replicate this for 4+ times, every time in the same line, even on a freshly forked image.
I think it is due to the building tool in the background.

Sadly, I'm no expert and can't give any more explainations or theories.
Here's a screenshot: 
![grafik](https://github.com/ublue-os/images-website/assets/99470494/2a134e6c-5faf-44e7-8648-ccde6dd70a58)

**Comment by xynydev** [comment]
Yeah, we're moving to BlueBuild as you saw on the front page of the site. This isn't an issue with the website, but the template and github action. Will be fixed soon.

**Comment by xynydev** [comment]
This is now fixed in the action, switch to v1.0.1 manually in build.yml if dependabot doesn't get that for you.
