### ISSUE TITLE
error getting boot menu

### ISSUE THREAD

**Issue by noahgiroux** [ublue-os/images-website#23]
When using the new site I get this:

`Repo created successfully! 
Updated repo information successfully! 
README got successfully! 
README updated successfully! 
Recipe got successfully! 
Recipe updated successfully! 
Error getting boot menu: 
{"message":"Not Found","documentation_url":"https://docs.github.com/rest/repos/contents#get-repository-content"}
!!!! 
Sorry, but repo creation cannot continue due to a fatal failure. Your new repo might have been left in a partially functional state, delete it to try again. You can report this to the sites issue tracker: https://github.com/ublue-os/images-website/issues. Remember to include logs, both from the console (enable XHR) and here.`

**Comment by xynydev** [comment]
Oh yeah, thanks. This file was removed a while back. Did you manage to finish your setup successfully after this? The fix would be pretty quick too, I'll try to do it today.

**Comment by noahgiroux** [comment]
Yeah I got through just thought I'd let you all know

**Comment by xynydev** [comment]
[bb02cac](https://github.com/blue-build/images-website/commit/bb02caca6a4a855f3fd55a4a5c80654722f2be63)
