### ISSUE TITLE
Site is not working 

### ISSUE THREAD

**Issue by awfixer** [ublue-os/images-website#25]
When I click thru the site I always end up on the following, no matter what platform or browser 
![Screenshot_20240409-021203](https://github.com/blue-build/images-website/assets/103541351/538677a2-9e1b-49de-9b73-d2e35ce4c709)

**Comment by xynydev** [comment]
Yeah, that URLs broken currently. Remind me where you clicked it again and I'll fix it there, would ya? The correct URL for now is https://ublue-images-demo.netlify.app/

**Comment by awfixer** [comment]
Let me test it, I believe this happened after I authorized GitHub

**Comment by awfixer** [comment]
## Screen recording from above mentioned link does not seem to be working if you want ping me in the blue build discord server I'm "imnotreallygir"

**Comment by jonerrr** [comment]
Looks like there's no DNS record present for createimage.blue-build.org. Maybe it got removed when switching the docs website to Cloudflare?

**Comment by xynydev** [comment]
Yup, it did. That messed up other domain stuff too. I gotta change the callback URL in GH. For now, one could theoritecally replace the domain in the URL after doing the auth.

**Comment by awfixer** [comment]
I'll play with it fs

**Comment by xynydev** [comment]
Ok I changed the callback URL so this should be fixed now
